AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template for creating DevOps group and user
Parameters: 
  DevOpsUserName:
    Type: String
    MinLength: 8
    MaxLength: 24
    Description: User name
    Default: DevOps-01
  DevOpsUserPassword:
    Type: String
    MinLength: 12
    MaxLength: 24
    NoEcho: true
    Description: Should be a complex password between 12-24 characters (i.e. 'T5^EyNF%hN70H')
Resources:
  DevOpsGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: DevOps
      Path: "/"
      ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/PowerUserAccess"
  DevOpsUser:
    Type: AWS::IAM::User
    DependsOn: DevOpsGroup
    Properties:
      UserName: !Ref DevOpsUserName
      Groups:
        - DevOps
      Path: "/"
      LoginProfile:
        Password: !Ref DevOpsUserPassword
  DevOpsUserAccessKey:
    Type: AWS::IAM::AccessKey
    DependsOn: DevOpsUser
    Properties:
      UserName: !Ref DevOpsUserName
Outputs:
  DevOpsUserArn:
    Description: The ARN of the DevOpsUser
    Value: !GetAtt 'DevOpsUser.Arn'
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'DevOpsUser' ] ]
  DevOpsUserAccessKeyId:
    Description: DevOpsUser AccessKeyId
    Value: !Ref DevOpsUserAccessKey  
  DevOpsUserSecretAccessKey:
    Description: DevOpsUser SecretAccessKey
    Value: !GetAtt DevOpsUserAccessKey.SecretAccessKey